# Generated by Django 4.1.3 on 2022-11-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursesapp", "0004_rename_course_curso"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("price", models.FloatField(max_length=10)),
                ("url", models.URLField(max_length=255)),
                ("category", models.CharField(max_length=50)),
                ("rating", models.FloatField(max_length=5)),
                ("language", models.CharField(max_length=4)),
                ("platform", models.CharField(max_length=20, null=True)),
                ("instructor", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(name="Curso",),
    ]
