# Generated by Django 4.1.3 on 2022-11-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursesapp", "0006_alter_courses_price_alter_courses_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="price",
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name="courses",
            name="rating",
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
