# Generated by Django 4.1.3 on 2022-11-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursesapp", "0007_alter_courses_price_alter_courses_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses", name="price", field=models.FloatField(max_length=5),
        ),
    ]
