# Generated by Django 4.1.3 on 2022-11-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursesapp", "0009_courses_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="instructor",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
