# Generated by Django 4.1.3 on 2022-11-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursesapp", "0010_alter_courses_instructor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.AutoField(max_length=10, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=150)),
                ("company", models.CharField(max_length=150)),
                ("location", models.CharField(max_length=100)),
                ("postDate", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                ("url", models.URLField(max_length=255)),
            ],
        ),
    ]
