# Generated by Django 4.1.3 on 2022-11-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursesapp", "0012_alter_job_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
