# Generated by Django 4.1.3 on 2022-11-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursesapp", "0014_alter_job_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
