# Generated by Django 4.1.3 on 2022-11-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0016_rename_bio_perfil_pais_rename_usuario_perfil_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(default='profile_images/default.png', null=True, upload_to='profile_images'),
        ),
    ]
