# Generated by Django 4.1.3 on 2022-11-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursesapp", "0017_alter_perfil_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=150)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("url", models.URLField(max_length=255)),
                ("category", models.TextField()),
                ("rating", models.DecimalField(decimal_places=1, max_digits=5)),
                ("language", models.CharField(max_length=4)),
                ("instructor", models.CharField(max_length=200, null=True)),
                ("description", models.TextField(null=True)),
                ("tags", models.TextField(null=True)),
                ("platform", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
