# Generated by Django 4.1.3 on 2022-11-23 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coursesapp", "0018_curso_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("soft_skill1", models.CharField(blank=True, max_length=255)),
                ("soft_skill2", models.CharField(blank=True, max_length=255)),
                ("soft_skill3", models.CharField(blank=True, max_length=255)),
                ("soft_skill4", models.CharField(blank=True, max_length=255)),
                ("soft_skill5", models.CharField(blank=True, max_length=255)),
                ("hard_skill1", models.CharField(blank=True, max_length=255)),
                ("hard_skill2", models.CharField(blank=True, max_length=255)),
                ("hard_skill3", models.CharField(blank=True, max_length=255)),
                ("hard_skill4", models.CharField(blank=True, max_length=255)),
                ("hard_skill5", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
