# Generated by Django 4.1.3 on 2022-11-22 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coursesapp', '0018_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='favorite',
            field=models.ManyToManyField(related_name='course_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
