# Generated by Django 4.1.3 on 2022-11-23 04:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coursesapp', '0020_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='favorite',
        ),
        migrations.AddField(
            model_name='curso',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
